 SELECT * FROM crime
 SELECT * FROM offense_codes

  SELECT COUNT (DISTINCT OFFENSE_DESCRIPTION)
  FROM crime

  SELECT YEAR, COUNT (SHOOTING) FROM crime
  WHERE SHOOTING = 'Y'
  GROUP BY YEAR
  ORDER BY YEAR

  SELECT COUNT(DISTINCT DISTRICT) 
  FROM crime

  SELECT COUNT (DISTINCT STREET)
  FROM crime

  SELECT  DISTINCT DISTRICT, COUNT(SHOOTING) AS DISTRICT_SHOOTINGS
  FROM crime
  WHERE SHOOTING = 'Y' 
  GROUP BY DISTRICT, SHOOTING
  ORDER BY DISTRICT_SHOOTINGS DESC

  SELECT COUNT(DISTINCT OFFENSE_CODE_GROUP)
  FROM crime

  SELECT DISTINCT OFFENSE_CODE_GROUP, OFFENSE_CODE, COUNT(OFFENSE_CODE_GROUP) AS NO_OF_OFFENSE
  FROM crime
  GROUP BY OFFENSE_CODE_GROUP, OFFENSE_CODE
  ORDER BY NO_OF_OFFENSE DESC

  SELECT COUNT(DISTINCT INCIDENT_NUMBER) AS UNIQUE_INCIDENTS
  FROM crime

  SELECT YEAR, COUNT(*) AS TOTAL_INCIDENTS
  FROM crime
  WHERE DISTRICT = 'C11'
  GROUP BY YEAR
  ORDER BY YEAR

  SELECT TOP 10 STREET, COUNT(*) AS TOTAL_INCIDENTS
  FROM crime
  WHERE STREET IS NOT NULL
  GROUP BY STREET
  ORDER BY TOTAL_INCIDENTS DESC

  SELECT DAY_OF_WEEK, COUNT(*) AS TOTAL_INCIDENTS
  FROM crime
  GROUP BY DAY_OF_WEEK
  ORDER BY TOTAL_INCIDENTS DESC

  SELECT OFFENSE_CODE, OFFENSE_DESCRIPTION, COUNT(*) AS TOTAL_INCIDENTS
  FROM crime
  GROUP BY OFFENSE_CODE, OFFENSE_DESCRIPTION
  ORDER BY TOTAL_INCIDENTS DESC
  
  SELECT DISTRICT, YEAR, MONTH, COUNT(*) AS TOTAL_INCIDENTS
  FROM crime
  WHERE DISTRICT IS NOT NULL AND YEAR = 2017
  GROUP BY DISTRICT, YEAR, MONTH
  ORDER BY DISTRICT, YEAR, MONTH

  SELECT TOP 10 DISTRICT, COUNT(*) AS TOTAL_INCIDENTS
  FROM crime
  WHERE DISTRICT IS NOT NULL
  GROUP BY DISTRICT
  HAVING COUNT(*) > 10000
  ORDER BY TOTAL_INCIDENTS DESC

  SELECT OFFENSE_CODE, OFFENSE_DESCRIPTION, YEAR, MONTH, COUNT (*) AS TOTAL_INCIDENTS
  FROM crime
  WHERE OFFENSE_CODE = '311'
  GROUP BY OFFENSE_CODE, OFFENSE_DESCRIPTION, YEAR, MONTH
  ORDER BY TOTAL_INCIDENTS DESC

  WITH COMMON_OFFENSES AS (
	   SELECT DISTRICT, OFFENSE_DESCRIPTION, COUNT(*) AS TOTAL_INCIDENTS
	   FROM crime
	   WHERE DISTRICT IS NOT NULL
	   GROUP BY DISTRICT, OFFENSE_DESCRIPTION
)
SELECT DISTRICT, OFFENSE_DESCRIPTION, TOTAL_INCIDENTS
FROM (
	   SELECT DISTRICT, OFFENSE_DESCRIPTION, TOTAL_INCIDENTS,
	   ROW_NUMBER() OVER (PARTITION BY DISTRICT ORDER BY TOTAL_INCIDENTS DESC) AS RN
	   FROM COMMON_OFFENSES
) RANKED 
	   WHERE RN <= 3

WITH CRIMEBYDAY AS (
	SELECT DISTRICT, DAY_OF_WEEK, COUNT(*) AS TOTAL_INCIDENTS
	FROM crime
	WHERE DISTRICT IS NOT NULL
	GROUP BY DISTRICT, DAY_OF_WEEK
)
SELECT DISTRICT, DAY_OF_WEEK, TOTAL_INCIDENTS
FROM (
	SELECT DISTRICT, DAY_OF_WEEK, TOTAL_INCIDENTS, 
			ROW_NUMBER() OVER (PARTITION BY DISTRICT ORDER BY TOTAL_INCIDENTS DESC) AS RN
	FROM CRIMEBYDAY
) RANKED
WHERE RN = 1

SELECT TOP 10 REPORTING_AREA, COUNT(*) AS TOTAL_INCIDENTS
FROM crime
WHERE REPORTING_AREA IS NOT NULL
GROUP BY REPORTING_AREA
ORDER BY TOTAL_INCIDENTS DESC

SELECT INCIDENT_NUMBER, DISTRICT, OCCURRED_ON_DATE, STREET, DAY_OF_WEEK, COUNT(*) AS SHOOTING_INCIDENT
FROM crime
WHERE SHOOTING = 'Y' 
GROUP BY INCIDENT_NUMBER, DISTRICT, STREET, DAY_OF_WEEK, OCCURRED_ON_DATE
ORDER BY SHOOTING_INCIDENT DESC

WITH SHOOTING_INCIDENTS AS (
     SELECT TOP 10 INCIDENT_NUMBER, DISTRICT, OCCURRED_ON_DATE, STREET, DAY_OF_WEEK, COUNT(*) AS SHOOTING_INCIDENT
	 FROM crime
	 WHERE SHOOTING = 'Y' 
	 GROUP BY INCIDENT_NUMBER, DISTRICT, STREET, DAY_OF_WEEK, OCCURRED_ON_DATE
	 ORDER BY SHOOTING_INCIDENT DESC 
)
SELECT STREET,
	   SUM(SHOOTING_INCIDENT) AS TOTAL_SHOOTING_INCIDENTS
FROM
	   SHOOTING_INCIDENTS
GROUP BY STREET
ORDER BY TOTAL_SHOOTING_INCIDENTS DESC
